export const groups = [
  {
    _id: 1,
    title: 'Təhsil',
  },
  {
    _id: 2,
    title: 'Səhiyyə',
  },
  {
    _id: 3,
    title: 'Aqrar',
  },
  {
    _id: 4,
    title: 'Mədəniyyət',
  },
  {
    _id: 5,
    title: 'Gömrük',
  },
  {
    _id: 6,
    title: 'Nəqliyyat rabitə',
  },
  {
    _id: 7,
    title: 'Dövlət idarələri',
  },
  {
    _id: 8,
    title: 'Neft qaz',
  },
  {
    _id: 9,
    title: 'Xidmət',
  },
  {
    _id: 10,
    title: 'Naxçıvan',
  },
  {
    _id: 11,
    title: 'Elektroenergetika',
  },
  {
    _id: 12,
    title: 'Dəmiryolçular',
  },
  {
    _id: 13,
    title: 'Avtonəqliyyat',
  },
  {
    _id: 14,
    title: 'FHN',
  },
  {
    _id: 15,
    title: 'Avrasiya',
  },
  {
    _id: 16,
    title: 'Dəniz',
  },
  {
    _id: 17,
    title: 'Müdafiə',
  },
  {
    _id: 18,
    title: 'Metropoliten',
  },
  {
    _id: 19,
    title: 'AMEA',
  },
  {
    _id: 20,
    title: 'Baku steel',
  },
  {
    _id: 21,
    title: 'Turizm',
  },
];

export const data = [
  {
    order: 1,
    checked: false,
    groupId: 1,
    name: 'Paşayev Araz Nadir oğlu',
    position: 'Elm və Təhsil İşçiləri Həmkarlar İttifaqının sədri',
  },
  {
    order: 2,
    checked: false,
    groupId: 1,
    name: 'Abdullayev Tehranağa Sadıq oğlu',
    position: 'Elm və Təhsil İşçiləri Həmkarlar İttifaqının sədrinin birinci müavini',
  },
  {
    order: 3,
    checked: false,
    groupId: 1,
    name: 'Cəfərzadə Mirzə Həkiməli oğlu',
    position: 'Elm və Təhsil İşçiləri Həmkarlar İttifaqının sədrinin müavini',
  },
  {
    order: 4,
    checked: false,
    groupId: 1,
    name: 'Kərimova Turanə Nahid qızı',
    position: 'Elm və Təhsil İşçiləri Həmkarlar İttifaqının sədrinin müavini',
  },
  {
    order: 5,
    checked: false,
    groupId: 1,
    name: 'Abbasov Yaşar Ağamirzə oğlu',
    position: 'Elm və Təhsil İşçiləri Həmkarlar İttifaqının Xaçmaz Rayon Komitəsinin sədri',
  },
  {
    order: 6,
    checked: false,
    groupId: 1,
    name: 'Xasiyeva Ziyafət Mustafa qızı',
    position: 'ETİHİ-Şəki Şəhər Komitəsinin sədri',
  },
  {
    order: 7,
    checked: false,
    groupId: 1,
    name: 'Əfəndiyeva Rübail Əhməd qızı',
    position: 'ETİHİ-Qax Rayon Komitəsinin sədri',
  },
  {
    order: 8,
    checked: false,
    groupId: 1,
    name: 'Ənvərli Misir Yusif oğlu',
    position: 'ETİHİ-Bərdə Rayon Komitəsinin sədri',
  },
  {
    order: 9,
    checked: false,
    groupId: 1,
    name: 'Səlimova Əfsanə Ədalət qızı',
    position: 'ETİHİ-Yevlax Şəhər Komitəsinin sədri',
  },
  {
    order: 10,
    checked: false,
    groupId: 1,
    name: 'Səmədova Kəmalə Qənbər qızı',
    position: 'ETİHİ-Göyçay Rayon Komitəsinin sədri',
  },
  {
    order: 11,
    checked: false,
    groupId: 1,
    name: 'Baxşıyeva Leyla Qabil qızı',
    position: 'ETİHİ-Səbail Rayon Komitəsinin sədri',
  },
  {
    order: 12,
    checked: false,
    groupId: 1,
    name: 'Novruzov Elşad Vaqif oğlu',
    position: 'ETİHİ-Sumqayıt Şəhər Komitəsinin sədri',
  },
  {
    order: 13,
    checked: false,
    groupId: 1,
    name: 'Nəbiyev Niyazi Hüseynalı oğlu',
    position: 'ETİHİ-Gəncə Şəhər Komitəsinin sədri',
  },
  {
    order: 14,
    checked: false,
    groupId: 1,
    name: 'Tağıyev Elçin Nağı oğlu',
    position: 'ETİHİ-Mingəçevir Dövlət Universiteti HİK sədri',
  },
  {
    order: 15,
    checked: false,
    groupId: 1,
    name: 'Qurbanov Habil Surxay oğlu',
    position: 'Elmi Təşkilatların Birləşmiş HİK sədri',
  },
  {
    order: 16,
    checked: false,
    groupId: 1,
    name: 'İsayev Siyasət İrzalı oğlu',
    position: 'ETİHİ-Mübariz İbrahimov adına Biləsuvar Bağça-Məktəb-Lisey Kompleksi HİK sədri',
  },
  {
    order: 17,
    checked: false,
    groupId: 1,
    name: 'Rəsullu Sevinc Raqib qızı',
    position: 'Bakı şəhəri üzrə Təhsil İdarəsi HİK sədri',
  },
  {
    order: 18,
    checked: false,
    groupId: 1,
    name: 'Cabarov Rəşad Eldar oğlu',
    position: 'Bakı Dövlət Universiteti HİK sədri',
  },
  {
    order: 19,
    checked: false,
    groupId: 1,
    name: 'Rəfili Şahmar Firqət oğlu',
    position: 'Azərbaycan Memarlıq və İnşaat Universiteti THİK sədri',
  },
  {
    order: 20,
    checked: false,
    groupId: 1,
    name: 'Əliyev Elnur Ələddin oğlu',
    position: 'ETİHİ-Elm və Təhsil Nazirliyi HİK sədri',
  },
  {
    order: 21,
    checked: false,
    groupId: 2,
    name: 'Muradova Elnara Nadir qızı',
    position: 'Azərbaycan Respublikası Səhiyyə İşçiləri Həmkarlar İttifaqının sədri',
  },
  {
    order: 22,
    checked: false,
    groupId: 2,
    name: 'Məmmədov Cavid   Mahal oğlu',
    position: 'Azərbaycan Respublikası Səhiyyə İşçiləri Həmkarlar İttifaqının sədrinin müavini',
  },
  {
    order: 23,
    checked: false,
    groupId: 2,
    name: 'Qasımov Cahangir  Lətif oğlu',
    position: 'Azərbaycan Tibb Universiteti Həmkarlar İttifaqı Komitəsinin sədri',
  },
  {
    order: 24,
    checked: false,
    groupId: 2,
    name: 'Bilalova Cahan  Nizami qızı',
    position:
      'Respublika Təcili və Təxirəsalınmaz Tibbi Yardım Mərkəzi Həmkarlar İttifaqı Komitəsinin sədri',
  },
  {
    order: 25,
    checked: false,
    groupId: 2,
    name: 'Cəfərov Həsən Şahhüseyn oğlu',
    position: 'Azərbaycan Həmkarlar İttifaqları Konfederasiyasının Aparat rəhbəri ',
  },
  {
    order: 26,
    checked: false,
    groupId: 2,
    name: 'Abdullayeva Qönçə  Faiq qızı',
    position: 'Azərbaycan Respublikası Səhiyyə İşçiləri Həmkarlar İttifaqının sədrinin müavini',
  },
  {
    order: 27,
    checked: false,
    groupId: 2,
    name: 'Rzayeva Yəmən Həsənalı qızı',
    position: 'Səhiyyə İşçiləri Həmkarlar İttifaqı Naxçıvan Muxtar Respublika Komitəsinin sədr',
  },
  {
    order: 28,
    checked: false,
    groupId: 2,
    name: 'Qurbanov Elcan   Vilayət oğlu',
    position: 'Gəncə şəhər Səhiyyə İşçiləri Həmkarlar İttifaqı Şurası  sədr',
  },
  {
    order: 29,
    checked: false,
    groupId: 2,
    name: 'Quliyeva Elmira  Əli qızı',
    position: 'Sumqayıt şəhər Səhiyyə İşçiləri Həmkarlar İttifaqı Şurası sədr ',
  },
  {
    order: 30,
    checked: false,
    groupId: 2,
    name: 'Alıyev Allahverdi Salman oğlu',
    position: 'Mingəçevir şəhər Səhiyyə İşçiləri Həmkarlar İttifaqı Şurası  sədr',
  },
  {
    order: 31,
    checked: false,
    groupId: 2,
    name: 'Eynullayev Rəşad  Allahverən',
    position: 'Lənkəran rayon Səhiyyə İşçiləri Həmkarlar İttifaqı Şurası  sədr',
  },
  {
    order: 32,
    checked: false,
    groupId: 2,
    name: 'Məmmədova Nurlana Vahid qızı',
    position: 'Yevlax rayon Səhiyyə İşçiləri Həmkarlar İttifaqı Şurası  sədr',
  },
  {
    order: 33,
    checked: false,
    groupId: 2,
    name: 'Fərəməzov Hikmət Hacıağa oğlu',
    position: 'Quba rayon Səhiyyə İşçiləri Həmkarlar İttifaqı Şurası  sədr',
  },
  {
    order: 34,
    checked: false,
    groupId: 2,
    name: 'Xankişiyeva İradə Maqsud qızı',
    position: 'Səbail rayon Səhiyyə İşçiləri Həmkarlar İttifaqı Şurası  sədr',
  },
  {
    order: 35,
    checked: false,
    groupId: 2,
    name: 'Balaşzadə Nizami Balaş oğlu',
    position: 'Yasamal rayon Səhiyyə İşçiləri Həmkarlar İttifaqı Şurası sədr',
  },
  {
    order: 36,
    checked: false,
    groupId: 2,
    name: 'Məmmədova Arifə Sədaqət qızı',
    position: 'Kliniki Tibbi Mərkəz Həmkarlar İttifaqı Komitəsi sədr',
  },
  {
    order: 37,
    checked: false,
    groupId: 2,
    name: 'Abbasova Leyla   Qasım qızı',
    position: 'Nərimanov Tibb Mərkəzi Həmkarlar İttifaqı Komitəsi sədr',
  },
  {
    order: 38,
    checked: false,
    groupId: 2,
    name: 'İsmayılova Günay Əliheydər qızı',
    position: 'Bakı Sağlamlıq Mərkəzi Həmkarlar İttifaqı Komitəsi sədr',
  },
  {
    order: 39,
    checked: false,
    groupId: 2,
    name: 'Hüseynov Azad  Vaqif oğlu',
    position: 'Ağcabədi rayon Səhiyyə İşçiləri Həmkarlar İttifaqı Şurası  sədr',
  },
  {
    order: 40,
    checked: false,
    groupId: 2,
    name: 'Rzayev Şahin  Vidadi oğlu',
    position: 'Şəmkir rayon Səhiyyə İşçiləri Həmkarlar İttifaqı Şurası  sədr',
  },
  {
    order: 41,
    checked: false,
    groupId: 3,
    name: 'Həsənov Məmməd  Arif oğlu',
    position:
      'AHİK sədrinin müşaviri,  Aqrar, Ekologiya və Su Təsərrüfatı İşçiləri Həmkarlar İttifaqı Respublika Birliyinin sədri',
  },
  {
    order: 42,
    checked: false,
    groupId: 3,
    name: 'İbadova Nuranə Akif qızı',
    position: 'AHİK sədrinin müşaviri',
  },
  {
    order: 43,
    checked: false,
    groupId: 3,
    name: 'Nəsibov Elvin Elşən oğlu',
    position:
      'Aqrar, Ekologiya və Su Təsərrüfatı İşçiləri Həmkarlar İttifaqı Respublika Birliyinin sədrinin birinci müavini',
  },
  {
    order: 44,
    checked: false,
    groupId: 3,
    name: 'Məmmədov Fuad Boris oğlu',
    position:
      'Aqrar, Ekologiya və Su Təsərrüfatı İşçiləri Həmkarlar İttifaqı Respublika Birliyinin sədrinin müavini',
  },
  {
    order: 45,
    checked: false,
    groupId: 3,
    name: 'Quliyev Telman Nəsirulla oğlu',
    position:
      'Aqrar, Ekologiya və Su Təsərrüfatı İşçiləri Həmkarlar İttifaqı Respublika Birliyinin sədrinin müavini',
  },
  {
    order: 46,
    checked: false,
    groupId: 3,
    name: 'Əsgərov Araz Səfər oğlu',
    position: 'Aparat rəhbəri',
  },
  {
    order: 47,
    checked: false,
    groupId: 3,
    name: 'Bürcəliyev Rüfət Azər oğlu',
    position: 'Sədrin müşaviri',
  },
  {
    order: 48,
    checked: false,
    groupId: 3,
    name: 'Əliyeva Səyyarə Haşım qızı',
    position: 'Şöbə müdiri',
  },
  {
    order: 49,
    checked: false,
    groupId: 3,
    name: 'Tağıyev Anar  Bəylər oğlu',
    position: 'Şöbə müdirinin müavini',
  },
  {
    order: 50,
    checked: false,
    groupId: 3,
    name: 'Tağızadə Elşad Şaməddin oğlu',
    position: 'Regional Su Meliorasiya Xidməti PHŞ-nin HİK-nin sədri',
  },
  {
    order: 51,
    checked: false,
    groupId: 3,
    name: 'Atayev Elnur Allahverdi oğlu',
    position: 'Kənd Təsərrüfatı Nazirliyinin aparatı HİK-nin sədri',
  },
  {
    order: 52,
    checked: false,
    groupId: 3,
    name: ' Məmmədova Aysel Telman qızı',
    position: 'Şöbə müdirinin müavini',
  },
  {
    order: 53,
    checked: false,
    groupId: 3,
    name: ' Cəfərova Günel Yaşar qızı',
    position: 'Şöbə müdirinin müavini',
  },
  {
    order: 54,
    checked: false,
    groupId: 3,
    name: ' Əliyeva Aygün Mais qızı',
    position: 'Baş mütəxəssis',
  },
  {
    order: 55,
    checked: false,
    groupId: 3,
    name: 'Əliyev Təhmasif Qaçay oğlu',
    position: 'Mütəxəssis',
  },
  {
    order: 56,
    checked: false,
    groupId: 3,
    name: 'Ələkbərova Arifə Gəncəli qızı',
    position: 'Baş texniki əmək müfəttişi',
  },
  {
    order: 57,
    checked: false,
    groupId: 3,
    name: ' Əhmədzadə Mələk Cuma qızı',
    position: 'Sahə Hİ Qax RK-nin sədri',
  },
  {
    order: 58,
    checked: false,
    groupId: 3,
    name: ' Əliyev Babək Əbülfət oğlu',
    position: 'Aqrar Xidmətlər Agentliyinin İlk HİK-nin sədri',
  },
  {
    order: 59,
    checked: false,
    groupId: 3,
    name: 'Hüseynov Ruslan Nazim oğlu',
    position: 'Aqroservis ASC-nin ilk HİK-nin sədri',
  },
  {
    order: 60,
    checked: false,
    groupId: 3,
    name: 'Rüstəmov Cabir Sədaqət oğlu',
    position: 'Regional HİK-nin sədri',
  },
  {
    order: 61,
    checked: false,
    groupId: 4,
    name: 'Məmmədov Sahib Əli oğlu',
    position: 'Azərbaycan Həmkarlar İttifaqları Konfederasiyasının sədri',
  },
  {
    order: 62,
    checked: false,
    groupId: 4,
    name: 'Ziyadov Elkiyar İkram oğlu',
    position: 'AHİK sədrinin müşaviri, Mədəniyyət İşçiləri Həmkarlar İttifaqının sədri',
  },
  {
    order: 63,
    checked: false,
    groupId: 4,
    name: 'Umudov Kamran Qəhəd oğlu',
    position: 'AHİK sədrinin müşaviri',
  },
  {
    order: 64,
    checked: false,
    groupId: 4,
    name: 'Atakişiyev Adil Aslan oğlu ',
    position: 'Mədəniyyət İşçiləri Həmkarlar İttifaqının sədrinin müavini',
  },
  {
    order: 65,
    checked: false,
    groupId: 4,
    name: 'Hüseynli Taleh Eldəniz oğlu ',
    position: 'Mədəniyyət İşçiləri Həmkarlar İttifaqının sədrinin müavini',
  },
  {
    order: 66,
    checked: false,
    groupId: 4,
    name: 'Quliyev Yusif Nazir oğlu ',
    position: 'Azərbaycan İdman Akademiyasının HİK sədri',
  },
  {
    order: 67,
    checked: false,
    groupId: 4,
    name: 'Rəhimli  Adil Rəhman oğlu',
    position: 'AHİK-in Əməyin və sağlamlığın  mühafizəsi şöbəsinin müdiri',
  },
  {
    order: 68,
    checked: false,
    groupId: 4,
    name: 'Abidinov Üzeyir Nizami oğlu',
    position: 'Mədəniyyət İşçiləri Həmkarlar İttifaqının sədrin müşaviri',
  },
  {
    order: 69,
    checked: false,
    groupId: 4,
    name: 'Süleymanova Rəminə Yaqub qızı',
    position:
      'Azərbaycan Respublikası Gənclər və İdman Nazirliyinin A3:C22Kollegiyasının məsul katibi, baş məsləhətçi',
  },
  {
    order: 70,
    checked: false,
    groupId: 4,
    name: 'Çingizzadə Elmar Vüqar oğlu',
    position: 'MİHİ-nin Maliyyə və təminat şöbəsinin müdiri-baş mühasib',
  },
  {
    order: 71,
    checked: false,
    groupId: 4,
    name: 'Əliyeva İradə Əbdül qızı',
    position: '“Azərbaycan” qəzetinin Humanitar-Siyasət şöbəsinin redaktoru',
  },
  {
    order: 72,
    checked: false,
    groupId: 4,
    name: 'Axundov Sahib İbrahim oğlu',
    position: 'MİHİ-nin Gəncə şəhər Komitəsinin sədri',
  },
  {
    order: 73,
    checked: false,
    groupId: 4,
    name: 'Qurbanov İsgəndər Kərəm oğlu',
    position: 'MİHİ-nin Qazax Rayon Komitəsinin sədri',
  },
  {
    order: 74,
    checked: false,
    groupId: 4,
    name: 'Məmmədova Səbinə Müzəffər qızı',
    position: 'Bakı Şəhər Mədəniyyət Baş İdarəsinin sektor müdiri',
  },
  {
    order: 75,
    checked: false,
    groupId: 4,
    name: 'Əzimov Telman Gözəl oğlu',
    position: 'MİHİ-nin Sabirabad rayon Komitəsinin sədri',
  },
  {
    order: 76,
    checked: false,
    groupId: 4,
    name: 'Manafov İkram Atabala oğlu',
    position: 'MİHİ-nin Abşeron rayon Komitəsinin sədri',
  },
  {
    order: 77,
    checked: false,
    groupId: 4,
    name: 'Əliyeva Nəzakət Muxtar qızı',
    position: 'MİHİ-nin Şəki rayon Komitəsinin sədri',
  },
  {
    order: 78,
    checked: false,
    groupId: 4,
    name: 'Əliyeva Arzu Akif qızı ',
    position:
      'Azərbaycan Respublikası Gənclər və İdman Nazirliyinin Kollegiyasının məsul katibi, baş məsləhətçi',
  },
  {
    order: 79,
    checked: false,
    groupId: 4,
    name: 'Nuriyeva Tünzalə Allahverdi qızı',
    position:
      '“Azərbaycan Televiziya və Radio Verilişləri” Qapalı Səhmdar Cəmiyyətinin HİK sədrinin vəzifəsini icra edən',
  },
  {
    order: 80,
    checked: false,
    groupId: 4,
    name: 'Muradova Arzu Hacıbaba qızı ',
    position: '“Azərtac” Dövlət Teleqraf Agentliyinin İdarə heyətinin sədrin müşaviri',
  },
  {
    order: 81,
    checked: false,
    groupId: 5,
    name: 'Namazov Rövşən Siyafiq oğlu',
    position: 'Azərbaycan Gömrük İşçiləri Həmkarlar İttifaqı Birliyinin sədri',
  },
  {
    order: 82,
    checked: false,
    groupId: 5,
    name: 'Ağayev Asəf Nəbi oğlu',
    position: 'Azərbaycan Gömrük İşçiləri Həmkarlar İttifaqı Birliyinin sədrinin müavini',
  },
  {
    order: 83,
    checked: false,
    groupId: 5,
    name: 'Alxasov Cavanşir Ağasəlim oğlu',
    position: 'Azərbaycan Gömrük İşçiləri Həmkarlar İttifaqı Birliyinin sədrinin müavini',
  },
  {
    order: 84,
    checked: false,
    groupId: 5,
    name: 'Mirzəzadə Şəhla Ziyad qızı',
    position:
      'Azərbaycan Respublikası Dövlət Gömrük Komitəsinin Tibbi Xidmət İdarəsinin İlk Həmkarlar İttifaqı Komitəsinin sədri ',
  },
  {
    order: 85,
    checked: false,
    groupId: 5,
    name: 'Məmmədova Nigar Mobil qızı',
    position:
      'Azərbaycan Respublikası Dövlət Gömrük Komitəsinin Hava Nəqliyyatında Baş Gömrük İdarəsi İşçilərinin İlk Həmkarlar İttifaqı Komitəsinin sədri',
  },
  {
    order: 86,
    checked: false,
    groupId: 5,
    name: 'Quliyeva Rəna Müşfiq qızı',
    position:
      'Azərbaycan Gömrük İşçiləri Həmkarlar İttifaqı Birliyinin sosial-sığorta üzrə aparıcı mütəxəssisi',
  },
  {
    order: 87,
    checked: false,
    groupId: 5,
    name: 'Məmmədova Kamalə Xalid qızı',
    position:
      'Azərbaycan Gömrük İşçiləri Həmkarlar İttifaqı Birliyinin kargüzarlıq işləri üzrə mütəxəssisi',
  },
  {
    order: 88,
    checked: false,
    groupId: 5,
    name: 'Muradov Adil Fazil oğlu',
    position:
      'Azərbaycan Respublikası Dövlət Gömrük Komitəsi Aparatı İşçilərinin İlk Həmkarlar İttifaqı Komitəsinin sədri',
  },
  {
    order: 89,
    checked: false,
    groupId: 5,
    name: 'Seyidov Azər Maşallah oğlu',
    position:
      'Azərbaycan Respublikası Dövlət Gömrük Komitəsinin Akademiyası İşçilərinin İlk Həmkarlar İttifaqı Komitəsinin sədri',
  },
  {
    order: 90,
    checked: false,
    groupId: 5,
    name: 'Gözəlova Aybəniz Sərdar qızı',
    position:
      'Azərbaycan Respublikası Dövlət Gömrük Komitəsinin Akademiyası Tələbələrinin İlk Həmkarlar İttifaqı Komitəsinin sədri',
  },
  {
    order: 91,
    checked: false,
    groupId: 5,
    name: 'Əzimov Eldar Rafiq oğlu',
    position:
      'Azərbaycan Respublikası Dövlət Gömrük Komitəsinin "Azərterminalkompleks" Birliyinin İşçilərinin İlk Həmkarlar İttifaqı Komitəsinin sədri',
  },
  {
    order: 92,
    checked: false,
    groupId: 5,
    name: 'Vəliyeva Arzu Muxtar qızı',
    position:
      'Azərbaycan Respublikası Dövlət Gömrük Komitəsinin "Azərterminalkompleks" Birliyinin İşçilərinin İlk Həmkarlar İttifaqı Komitəsinin sədr müavini',
  },
  {
    order: 93,
    checked: false,
    groupId: 5,
    name: 'Seyidov Samir Maarif oğlu',
    position:
      'Azərbaycan Respublikası Dövlət Gömrük Komitəsinin Aksizli Mallar üzrə Baş Gömrük İdarəsi İşçilərinin İlk Həmkarlar İttifaqı Komitəsinin sədri',
  },
  {
    order: 94,
    checked: false,
    groupId: 5,
    name: 'Ayvazova Aysel Akif qızı',
    position:
      'Azərbaycan Respublikası Dövlət Gömrük Komitəsinin Avtomobil Nəqliyyatı İdarəsi İşçilərinin İlk Həmkarlar İttifaqı Tşkilatının sədri',
  },
  {
    order: 95,
    checked: false,
    groupId: 5,
    name: 'Alməmmədov Orxan Rüstəm oğlu',
    position:
      'Azərbaycan Respublikası Dövlət Gömrük Komitəsinin Bakı Baş Gömrük İdarəsi İşçilərinin\r\n İlk Həmkarlar İttifaqı Komitəsinin sədri  ',
  },
  {
    order: 96,
    checked: false,
    groupId: 5,
    name: 'Xəlilova Turan Əfqan qızı',
    position:
      'Azərbaycan Respublikası Dövlət Gömrük Komitəsinin Baş Gömrük Mühafizə Xidməti İşçilərinin İlk Həmkarlar İttifaqı Komitəsinin sədr müavini ',
  },
  {
    order: 97,
    checked: false,
    groupId: 5,
    name: 'Mahmudov Nicat İlham oğlu',
    position:
      'Azərbaycan Respublikası Dövlət Gömrük Komitəsinin Dəniz Nəqliyyatı və Enerji Resursları Baş Gömrük İdarəsi İşçilərinin İlk Həmkarlar İttifaqı Komitəsinin sədri ',
  },
  {
    order: 98,
    checked: false,
    groupId: 5,
    name: 'Yarəliyev Bəxtiyar Saməddin oğlu',
    position:
      'Azərbaycan Respublikası Dövlət Gömrük Komitəsinin Mərkəzi Gömrük Ekspertizası İdarəsi\r\n İşçilərinin İlk Həmkarlar İttifaqı Komitəsinin sədri',
  },
  {
    order: 99,
    checked: false,
    groupId: 5,
    name: 'Abdullayeva Şəhla Nəsir qızı',
    position:
      'Azərbaycan Respublikası Dövlət Gömrük Komitəsinin "Poçt və Ekspres Daşımalar" Gömrük Postu\r\n İşçilərinin İlk Həmkarlar İttifaqı Tşkilatının sədri',
  },
  {
    order: 100,
    checked: false,
    groupId: 5,
    name: 'Tərlanlı Səyyad Səyyar oğlu',
    position:
      'Azərbaycan Respublikası Dövlət Gömrük Komitəsinin Sumqayıt Gömrük İdarəsi İşçilərinin\r\n İlk Həmkarlar İttifaqı Komitəsinin sədri',
  },
  {
    order: 101,
    checked: false,
    groupId: 6,
    name: 'Əmirov Müşviq Vaqif oğlu',
    position:
      'Azərbaycan Nəqliyyat, Rabitə və Yüksək Texnologiya  İşçiləri Həmkarlar İttifaqının sədri',
  },
  {
    order: 102,
    checked: false,
    groupId: 6,
    name: 'Səfərov Rəşad Akif oğlu',
    position:
      'Azərbaycan Nəqliyyat, Rabitə və Yüksək Texnologiya  İşçiləri Həmkarlar İttifaqının sədrinin müavini',
  },
  {
    order: 103,
    checked: false,
    groupId: 6,
    name: 'Əhmədov Yaşar Məhərrəm oğlu',
    position: 'Hİ Bakı-1 şöbəsinin sədri (Aztelekom MMC)',
  },
  {
    order: 104,
    checked: false,
    groupId: 6,
    name: 'İsayev Etibar Ələkbər oğlu',
    position: 'Baktelekom MMC-nin BHİK sədri',
  },
  {
    order: 105,
    checked: false,
    groupId: 6,
    name: 'Səmədov Nüsrət Səməd oğlu',
    position: 'Hİ Bakı-2 şöbəsinin sədri (Azərpoçt MMC)',
  },
  {
    order: 106,
    checked: false,
    groupId: 6,
    name: 'Cahangirov Rövşən Asif oğlu',
    position: 'Sədrin müşaviri',
  },
  {
    order: 107,
    checked: false,
    groupId: 6,
    name: 'Məmmədov Amil Böyükkişi oğlu',
    position: 'Katib-Maliyyə şöbəsinin müdiri',
  },
  {
    order: 108,
    checked: false,
    groupId: 6,
    name: 'Tağıyev Malik Mirzəxan oğlu',
    position: 'Nazirliyin Maliyyə şöbəsinin müdir müavini',
  },
  {
    order: 109,
    checked: false,
    groupId: 6,
    name: 'Nəsibov Fərid Rasim oğlu',
    position: 'Təşkilat işləri və beynəlxalq əlaqələr şöbəsinin müdiri',
  },
  {
    order: 110,
    checked: false,
    groupId: 6,
    name: 'Ağrılı Aliyə Reyman qızı',
    position: 'Təşkilat işləri və beynəlxalq əlaqələr şöbəsinin müdir müavini',
  },
  {
    order: 111,
    checked: false,
    groupId: 6,
    name: 'İbrahimova Zərifə Əbülfət qızı',
    position: 'Təşkilat işləri və beynəlxalq əlaqələr şöbəsinin baş mütəxəssisi',
  },
  {
    order: 112,
    checked: false,
    groupId: 6,
    name: 'Hüseynli Anar Məmməd oğlu',
    position: 'Əməyin baş hüquq müfəttişi',
  },
  {
    order: 113,
    checked: false,
    groupId: 6,
    name: 'Qarayev Araz Azər oğlu',
    position: 'Əməyin baş texniki müfəttişi',
  },
  {
    order: 114,
    checked: false,
    groupId: 6,
    name: 'Nəcəfova Şəfəq Tofiq qızı',
    position:
      'Mərkəzi Rabitə İdarəsinin Məxfi işlər və rejim şöbəsinin sənədlərlə iş üzrə mühəndisi',
  },
  {
    order: 115,
    checked: false,
    groupId: 6,
    name: 'Dilanova Nuridə Əhəd qızı',
    position: 'Medianın İnkişafı Agentliyinin HİK sədri',
  },
  {
    order: 116,
    checked: false,
    groupId: 6,
    name: 'Abasov Ağəli Əvəz oğlu',
    position: 'Azərkosmos ASC-nin HİK sədri',
  },
  {
    order: 117,
    checked: false,
    groupId: 6,
    name: 'Hüseynzadə Orxan Elgiz oğlu',
    position: 'Azərbaycan Yerüstü Nəqliyyat Agentliyinin HİK sədri',
  },
  {
    order: 118,
    checked: false,
    groupId: 6,
    name: 'Məmmədov Anar İlyas oğlu',
    position: 'Hərbiləşmiş Mühafizə İdarəsinin HİK sədri',
  },
  {
    order: 119,
    checked: false,
    groupId: 6,
    name: 'Mahmudova Nəzakət Zakir qızı',
    position: 'Teleradio İB-in HİK sədri',
  },
  {
    order: 120,
    checked: false,
    groupId: 6,
    name: 'Əliyeva Aidə Nazim qızı',
    position: '“Azintelekom” MMC-nin HİK sədri',
  },
  {
    order: 121,
    checked: false,
    groupId: 7,
    name: 'Nəbiyev Hikmət Sədi oğlu',
    position: 'ADİİXİ Respublika Komitəsinin sədri',
  },
  {
    order: 122,
    checked: false,
    groupId: 7,
    name: 'Quliyev Cəmaləddin Əlibala oğlu ',
    position: 'ADİİXİ Respublika Komitəsinin sədrinin I müavini',
  },
  {
    order: 123,
    checked: false,
    groupId: 7,
    name: 'Vahabzadə Nigar Mirqasım qızı',
    position: 'Turizm və Ekskursiyalar üzrə Azərbaycan Respublika Şurasının sədri',
  },
  {
    order: 124,
    checked: false,
    groupId: 7,
    name: 'Məmmədov Fuad Adil oğlu',
    position: 'ADİİXİ Ədliyyə Nazirliyi BHİK-nin sədri',
  },
  {
    order: 125,
    checked: false,
    groupId: 7,
    name: 'Ağayeva Firənginaz Əhməd qızı',
    position: 'ADİİXİ Respublika Komitəsinin təşkilati işlər və\r\nməlumat şöbəsinin müdiri',
  },
  {
    order: 126,
    checked: false,
    groupId: 7,
    name: 'Əlizadə Murad İsrafil oğlu ',
    position: 'AHİK-in Protokol şöbəsinin müdiri',
  },
  {
    order: 127,
    checked: false,
    groupId: 7,
    name: 'Dəmirli Elvin Sərxan oğlu',
    position:
      'AHİK-in Media və kommunikasiya şöbəsinin müdir müavini, şöbə müdiri vəzifəsini müvəqqəti icra edən',
  },
  {
    order: 128,
    checked: false,
    groupId: 7,
    name: 'Qasımov Rəhim Məcnun oğlu',
    position: 'ADİİXİ Respublika Komitəsinin sədr müavini',
  },
  {
    order: 129,
    checked: false,
    groupId: 7,
    name: 'Əhmədov Şaiq Ruslan oğlu',
    position: 'ADİİXİ Respublika Komitəsinin aparat rəhbəri,\r\naparat işçiləri HİK-nin sədri',
  },
  {
    order: 130,
    checked: false,
    groupId: 7,
    name: 'Rzayev Kərim Məmməd oğlu ',
    position: 'ADİİXİ Müdafiə Nazirliyi BHİK-nin sədri;',
  },
  {
    order: 131,
    checked: false,
    groupId: 7,
    name: 'Pənahov Fəxrəddin Ataxan oğlu',
    position: 'ADİİXİ Daxili İşlər Nazirliyi BHİK-nin sədri',
  },
  {
    order: 132,
    checked: false,
    groupId: 7,
    name: 'Əliyev Ayaz Elman oğlu',
    position: 'ADİİXİ İqtisadiyyat Nazirliyi BHİK-nin sədri',
  },
  {
    order: 133,
    checked: false,
    groupId: 7,
    name: 'Musayev Fuad Məmməd oğlu ',
    position: 'ADİİXİ Əmək və Əhalinin Sosial Müdafiəsi Nazirliyi BHİK-nin sədri ',
  },
  {
    order: 134,
    checked: false,
    groupId: 7,
    name: 'Həbiyev İlqar İgid oğlu',
    position:
      'ADİİXİ İqtisadiyyat Nazirliyi yanında Əmlak Məsələləri Dövlət Xidməti BHİK-nin sədri',
  },
  {
    order: 135,
    checked: false,
    groupId: 7,
    name: 'Mahmudov Eldar Şirəli oğlu ',
    position: 'ADİİXİ Maliyyə Nazirliyi HİK-nin sədri',
  },
  {
    order: 136,
    checked: false,
    groupId: 7,
    name: 'Məmmədov Pərviz Vaqif oğlu',
    position: 'ADİİXİ Аli  Məhkəmə HİK-nin sədri',
  },
  {
    order: 137,
    checked: false,
    groupId: 7,
    name: 'Məhərrəmov Məhəmməd Yusif oğlu',
    position: 'ADİİXİ Yeni Azərbaycan Partiyası HİK-nin sədri',
  },
  {
    order: 138,
    checked: false,
    groupId: 7,
    name: 'Mehdizadə Firudin Zülfiqar oğlu',
    position:
      'ADİİXİ  Hİ Azərbaycan İqtisadiyyat Nazirliyi yanında Dövlət Vergi Xidməti BHİK-in Sədri',
  },
  {
    order: 139,
    checked: false,
    groupId: 7,
    name: 'Babayev Qüdrət Əhməd oğlu ',
    position: 'ADİİXİ Şəki şəhər komitəsinin sədri',
  },
  {
    order: 140,
    checked: false,
    groupId: 7,
    name: 'Məmmədov Tahir Əlməmməd oğlu',
    position: 'ADİİXİ Xaçmaz rayon komitəsinin sədri',
  },
  {
    order: 141,
    checked: false,
    groupId: 8,
    name: 'Zamanov Rüfət Firdovsi oğlu',
    position: 'Azərbaycan Neft və Qaz Sənayesi İşçiləri Həmkarlar İttifaqının sədri',
  },
  {
    order: 142,
    checked: false,
    groupId: 8,
    name: 'Mustafayev Fətulla Ramiz oğlu',
    position: 'Azərbaycan Neft və Qaz Sənayesi İşçiləri Həmkarlar İttifaqının sədrinin müavini',
  },
  {
    order: 143,
    checked: false,
    groupId: 8,
    name: 'Əsgərov Heydər Əli oğlu',
    position:
      'Azərbaycan Neft və Qaz Sənayesi İşçiləri Həmkarlar İttifaqının Təşkilat şöbəsinin müdiri',
  },
  {
    order: 144,
    checked: false,
    groupId: 8,
    name: 'Qurbanov Ədalət Qənbər oğlu',
    position: 'Azəriqaz İstehsalat Birliyi HİK sədri',
  },
  {
    order: 145,
    checked: false,
    groupId: 8,
    name: 'Xəlilov Aydın Raiq oğlu',
    position: 'Azərikimya İstehsalat Birliyi HİK sədri',
  },
  {
    order: 146,
    checked: false,
    groupId: 8,
    name: 'Nəsibov Eldar Kamal oğlu',
    position: 'RK Aparat HİK sədri',
  },
  {
    order: 147,
    checked: false,
    groupId: 8,
    name: 'Vəliyev Nazim Aslan oğlu',
    position: 'SOCAR Baş ofis HİK sədri',
  },
  {
    order: 148,
    checked: false,
    groupId: 8,
    name: 'Məsimova Xalidə Məhəmməd qızı',
    position: 'AR Energetika Nazirliyi HİK sədri',
  },
  {
    order: 149,
    checked: false,
    groupId: 8,
    name: 'Quliyev İlham Hilal oğlu',
    position: 'H.Əliyev adına Neft Emalı Zavodu HİK sədri',
  },
  {
    order: 150,
    checked: false,
    groupId: 8,
    name: 'Qurbanov Əli Səxavət oğlu',
    position: 'Neftqaztikinti tresti HİK sədri',
  },
  {
    order: 151,
    checked: false,
    groupId: 8,
    name: 'Əhmədov Nazim Əyyub oğlu',
    position: 'Kompleks Qazma İşləri tresti HİK sədri',
  },
  {
    order: 152,
    checked: false,
    groupId: 8,
    name: 'Kərimov Aqil Fərhad oğlu',
    position: 'SOCAR Nəqliyyat İdarəsi HİK sədri',
  },
  {
    order: 153,
    checked: false,
    groupId: 8,
    name: 'Əliyev Rəşad Əmirşah oğlu',
    position: 'Neft Daşları Neft Qaz Çıxarma İdarəsi HİK sədri',
  },
  {
    order: 154,
    checked: false,
    groupId: 8,
    name: 'Əsədova Esmira Fərəməz qızı',
    position: 'Surakhani Oil Operation Company S.A. HİK sədri\r\n',
  },
  {
    order: 155,
    checked: false,
    groupId: 8,
    name: 'Həsənov Nazim Qəmbər oğlu',
    position: 'SOCAR İnformasiya Texnologiyaları və Rabitə İdarəsi HİK sədri',
  },
  {
    order: 156,
    checked: false,
    groupId: 8,
    name: 'Caniyev Elnur Xulqat oğlu',
    position: 'RK sədrinin müşaviri',
  },
  {
    order: 157,
    checked: false,
    groupId: 8,
    name: 'Məmmədov Emin Şofir oğlu',
    position: '28 May  Neft Qaz Çıxarma İdarəsi HİK sədri',
  },
  {
    order: 158,
    checked: false,
    groupId: 8,
    name: 'Mustafayev Ramiz Fətulla oğlu',
    position: 'SOCAR Petroleum QSC HİK sədri',
  },
  {
    order: 159,
    checked: false,
    groupId: 8,
    name: 'Məmmədov Taleh Mirkərəm oğlu',
    position: 'Shirvan Operating Company LTD şirkəti HİK sədri',
  },
  {
    order: 160,
    checked: false,
    groupId: 8,
    name: 'Rzayev Xankişi Əlisahib oğlu',
    position: 'Azneft İB 1 saylı İtisaslaşdırılmış Neft-Mədən Xüsusi Texnika idarəsiHİK sədri',
  },
  {
    order: 161,
    checked: false,
    groupId: 9,
    name: 'Ələkbərov Fuad Fərman oğlu',
    position: 'Xidmət və Sənaye İşçiləri Həmkarlar İttifaqı Respublika Birliyinin sədri',
  },
  {
    order: 162,
    checked: false,
    groupId: 9,
    name: 'Əliyev İlyas Alxas oğlu',
    position:
      'Xidmət və Sənaye İşçiləri Həmkarlar İttifaqı Respublika Birliyinin sədrinin birinci müavini',
  },
  {
    order: 163,
    checked: false,
    groupId: 9,
    name: 'Məmmədov Mübariz Teymur oğlu',
    position: '“Holçim”-MMC HİK-in sədri',
  },
  {
    order: 164,
    checked: false,
    groupId: 9,
    name: 'Hümmətov Məhəmməd Namiq oğlu',
    position: 'AHİK sədrinin müşaviri',
  },
  {
    order: 165,
    checked: false,
    groupId: 9,
    name: 'Məmmədov Sabir İsmayıl oğlu',
    position: '\r\n"Azpetrol LTD" MMC HİK-in sədri \r\n',
  },
  {
    order: 166,
    checked: false,
    groupId: 9,
    name: 'Cahangirov Lətif Ramiz oğlu',
    position: 'AHİK-in Daxili nəzarət şöbəsinin müdiri',
  },
  {
    order: 167,
    checked: false,
    groupId: 9,
    name: 'Qasımov Tural Məhərrəm oğlu',
    position: 'Sədrin müavini',
  },
  {
    order: 168,
    checked: false,
    groupId: 9,
    name: 'Bağırov Fəzail Ağamməd oğlu',
    position: 'Sədrin müavini',
  },
  {
    order: 169,
    checked: false,
    groupId: 9,
    name: 'Abasov Mirkazım Mircabbar oğlu',
    position: 'Sədrin müavini',
  },
  {
    order: 170,
    checked: false,
    groupId: 9,
    name: 'Hüseynov Tofiq Teymurxan oğlu',
    position: 'Əməyin baş \r\ntexniki müfəttişi',
  },
  {
    order: 171,
    checked: false,
    groupId: 9,
    name: 'İsmayılov Cəmaləddin Köçəri oğlu',
    position: 'Sədrin müşaviri',
  },
  {
    order: 172,
    checked: false,
    groupId: 9,
    name: 'Həmidov Mətləb Əbdülhəmid oğlu',
    position: 'HİK-sədri Bakı \r\nNeft maşın \r\nqayırma zavodu',
  },
  {
    order: 173,
    checked: false,
    groupId: 9,
    name: 'Abasov Müşfiq Səxavət oğlu',
    position: 'Layihələrin idarəedilməsi \r\nşöbəsinin Şöbə \r\nmüdirinin müavini',
  },
  {
    order: 174,
    checked: false,
    groupId: 9,
    name: 'Hüseynov Rövşən Ənvər oğlu',
    position: 'Xətai rayon HİK sədri',
  },
  {
    order: 175,
    checked: false,
    groupId: 9,
    name: 'Cabbarov Cavad Əmrəddin oğlu',
    position: 'Maliyyə şöbəsinin \r\nmüavini və Təminat ',
  },
  {
    order: 176,
    checked: false,
    groupId: 9,
    name: 'Quliyev Siyasət Mehman oğlu',
    position: 'Suraxanı rayon HİK sədri',
  },
  {
    order: 177,
    checked: false,
    groupId: 9,
    name: 'Niftəliyev Tural Akif oğlu',
    position: '“Carlsberg Azerbaijan” \r\n(Xırdalan)-Pivə \r\nZavodunun HİK sədri',
  },
  {
    order: 178,
    checked: false,
    groupId: 9,
    name: 'Orucov Kamran Əliş oğlu',
    position: 'Abşeron rayon HİK sədri',
  },
  {
    order: 179,
    checked: false,
    groupId: 9,
    name: 'İsmayılov Seyfulla Eynulla oğlu',
    position: 'Layihələrin idarəedilməsi şöbəsinin Baş mütəxəsisi',
  },
  {
    order: 180,
    checked: false,
    groupId: 9,
    name: 'Muradova Zöhrə Sultan qızı',
    position: 'Binəqədi rayon HİK sədrinin müavini ',
  },
  {
    order: 181,
    checked: false,
    groupId: 10,
    name: 'Abdullayev Qəzənfər İsmayıl oğlu',
    position:
      'AHİK sədrinin müavini, Naxçıvan Muxtar Respublikası Həmkarlar İttifaqları Şurasının sədri',
  },
  {
    order: 182,
    checked: false,
    groupId: 10,
    name: 'İbrahimli Xatirə Mikayıl qızı',
    position: 'Naxçıvan Muxtar Respublikası Həmkarlar İttifaqları Şurasının sədrinin müavini',
  },
  {
    order: 183,
    checked: false,
    groupId: 10,
    name: 'Nur Günel Alməmməd qızı',
    position:
      'Naxçıvan Muxtar Respublikası Həmkarlar İttifaqları Şurasının Mətbuat və ictimaiyyətlə əlaqələr şöbənin müdiri',
  },
  {
    order: 184,
    checked: false,
    groupId: 10,
    name: 'Məmmədov Ceyhun İmran oğlu',
    position:
      'Naxçıvan Muxtar Respublikası Həmkarlar İttifaqları Şurasının Təşkilati-metodiki şöbənin müdiri',
  },
  {
    order: 185,
    checked: false,
    groupId: 10,
    name: 'Kələşov İmran Əmiraslan oğlu',
    position:
      'Naxçıvan Muxtar Respublikası Həmkarlar İttifaqları Şurasının Maliyyə şöbəsinin müdiri',
  },
  {
    order: 186,
    checked: false,
    groupId: 10,
    name: 'Əsgərov Elnur Lazar oğlu',
    position: 'Naxçıvan Muxtar Respublikası Həmkarlar İttifaqları Şurasında sədrin müşaviri',
  },
  {
    order: 187,
    checked: false,
    groupId: 10,
    name: 'Əsgərov  Eyvaz Mustafa oğlu',
    position:
      'Naxçıvan Muxtar Respublikası Həmkarlar İttifaqları Şurasının Əməyin və sosial iqtisadi mənafelərin müdafiəsi şöbəsinin müdiri',
  },
  {
    order: 188,
    checked: false,
    groupId: 10,
    name: 'Əliyeva Zümrüd Elçin qızı',
    position:
      'Naxçıvan Muxtar Respublikası Həmkarlar İttifaqları Şurasının  Ümumi işlər bölməsinin müdiri',
  },
  {
    order: 189,
    checked: false,
    groupId: 10,
    name: ' Fətəlixanlı Hüseyn Çərkəz oğlu',
    position: 'Təhsil İşçiləri Həmkarlar İttifaqi Naxçıvan Muxtar Respublika Komitəsinin sədri',
  },
  {
    order: 190,
    checked: false,
    groupId: 10,
    name: 'Novruzova Ülvüyə Mehdi qızı',
    position:
      'Dövlət və Bələdiyyə İdarələri İşçiləri Həmkarlar İttifaqı Naxçıvan Muxtar RespublikaKomitəsinin sədri',
  },
  {
    order: 191,
    checked: false,
    groupId: 10,
    name: 'Qulamov Şahin İdris oğlu',
    position:
      'Tikinti- Memarlıq,  Kommunal İctimai Xidmət Müəssisələri İşçiləri Həmkarlar İttifaqı Naxçıvan Muxtar Respublika Komitəsinin sədri',
  },
  {
    order: 192,
    checked: false,
    groupId: 10,
    name: 'Məmmədov Zaur Əvəz oğlu',
    position:
      'Naxçıvan Muxtar Respublikası Rabitə İşçiləri Birləşmiş Həmkarlar İttifaqi Komitəsinin sədri',
  },
  {
    order: 193,
    checked: false,
    groupId: 10,
    name: 'Məmmədov Elçin Vaqif oğlu',
    position: 'Şərur rayon Birləşmiş Həmkarlar İttifaqı Komitəsinin sədri',
  },
  {
    order: 194,
    checked: false,
    groupId: 10,
    name: 'Əkbərli Fariz Vüqar oğlu',
    position: 'Ordubad rayon Birləşmiş Həmkarlar İttifaqı Komitəsinin sədri',
  },
  {
    order: 195,
    checked: false,
    groupId: 10,
    name: 'Kərimov Mirhəsən  Mirhüseyn oğlu',
    position: 'Şahbuz rayon Birləşmiş Həmkarlar İttifaqı Komitəsinin sədri',
  },
  {
    order: 196,
    checked: false,
    groupId: 10,
    name: 'Abbasov Famil Ənnağı oğlu',
    position: 'Kəngərli rayon Birləşmiş Həmkarlar İttifaqı Komitəsinin  sədri',
  },
  {
    order: 197,
    checked: false,
    groupId: 10,
    name: 'Abbasov Elşən Tapdıq oğlu',
    position: 'Babək rayon Birləşmiş Həmkarlar İttifaqı Komitəsinin  Sədri',
  },
  {
    order: 198,
    checked: false,
    groupId: 10,
    name: 'Məmmədli Arzuman Sultanəli oğlu',
    position: 'Culfa rayon Birləşmiş Həmkarlar İttifaqı Komitəsinin  sədri',
  },
  {
    order: 199,
    checked: false,
    groupId: 10,
    name: 'Hüseynov Sənan Bahadur oğlu',
    position: 'Sədədrək rayon Birləşmiş Həmkarlar İttifaqı  Komitəsinin sədri',
  },
  {
    order: 200,
    checked: false,
    groupId: 10,
    name: 'Nəbiyeva Nəzakət Məmməd qızı',
    position:
      'Təhsil İşçiləri  Həmkarlar İttifaqi Naxçıvan Muxtar Respublika Komitəsinin təlimatçısı',
  },
  {
    order: 201,
    checked: false,
    groupId: 11,
    name: ' Mirzəyev Musa İbrahim oğlu',
    position:
      'AHİK sədrinin müavini, Elektroenergetika və Kommunal Müəssisələri İşçiləri Həmkarlar İttifaqı Respublika Birliyinin sədri',
  },
  {
    order: 202,
    checked: false,
    groupId: 11,
    name: 'Hacıyev Telman Həbib oğlu',
    position:
      'Elektroenergetika və Kommunal Müəssisələri İşçiləri Həmkarlar İttifaqı Respublika Birliyinin sədrinin müavini',
  },
  {
    order: 203,
    checked: false,
    groupId: 11,
    name: 'Mustafayev Şöhrət Oruc oğlu',
    position:
      'Elektroenergetika və Kommunal Müəssisələri İşçiləri Həmkarlar İttifaqı Respublika Birliyininin Təşkilat şöbəsinin müdiri',
  },
  {
    order: 204,
    checked: false,
    groupId: 11,
    name: 'Əlizadə Hicran Müseyib qızı',
    position: '"Azərenerji" ASC-nin BHİK-in sədri',
  },
  {
    order: 205,
    checked: false,
    groupId: 11,
    name: 'Məcidov Elşən  Məcid oğlu',
    position: '“Azərişıq”ASC-nin Həmkarlar İttifaqı Birliyinin sədri',
  },
  {
    order: 206,
    checked: false,
    groupId: 11,
    name: ' Musayeva Aygün Elxan qızı',
    position: 'Respublika Birliyinin Maliyyə şöbəsinin müdiri',
  },
  {
    order: 207,
    checked: false,
    groupId: 11,
    name: 'Allahverdova Səadət Yusif qızı',
    position: 'Respublika Birliyinin aparıcı mütəxəssisi',
  },
  {
    order: 208,
    checked: false,
    groupId: 11,
    name: 'Həmidov Şahiddin Əlfəddin oğlu',
    position: 'Respublika Birliyinin Əməyin və sağlamlığın mühafizəsi sektorunun müdiri',
  },
  {
    order: 209,
    checked: false,
    groupId: 11,
    name: 'Yusifova Nigar Namiq qızı',
    position: 'Respublik Birliyinin baş mütəxəssisi',
  },
  {
    order: 210,
    checked: false,
    groupId: 11,
    name: 'Səlimova Afaq Kamil qızı',
    position:
      '«Azərbaycan Elmi-Tədqiqat və Layihə Axtarış\r\n Energetika İnstitutu» MMC, HİK-in sədri',
  },
  {
    order: 211,
    checked: false,
    groupId: 11,
    name: 'Cəfərov Vüsət Valeh oğlu',
    position:
      '“Sumqayıt YGEŞ”MMC, HİK-in sədri, \r\nRespublik Birliyinin Təftiş komissiyasının sədri',
  },
  {
    order: 212,
    checked: false,
    groupId: 11,
    name: 'Əliyev  Əbdül Təvəkkül oğlu\r\n',
    position: 'Mingəçevir şəhər HİK-in sədri',
  },
  {
    order: 213,
    checked: false,
    groupId: 11,
    name: 'Hüseynova Zenfira Hüseyn qızı\r\n',
    position: 'Bakı Şəhər İcra Hakimiyyəti Yaşıllaşdırma \r\nTəsərrüfatı Birliyinin HİK-in sədri',
  },
  {
    order: 214,
    checked: false,
    groupId: 11,
    name: 'İbrahimovaTəranə İmran qızı\r\n',
    position: 'Sumqayıt şəhər HİK-in sədri',
  },
  {
    order: 215,
    checked: false,
    groupId: 11,
    name: 'Quliyeva Nigar Hacıağa qızı\r\n',
    position: '“Bakı Şəhər İşığı” Elektrik Şəbəkə Müəssisəsi, \r\nHİK-in sədr',
  },
  {
    order: 216,
    checked: false,
    groupId: 11,
    name: ' Məmmədov İsmayıl Baba oğlu\r\n',
    position: '«Xaçmaz REŞ» MMC, HİK-in sədri',
  },
  {
    order: 217,
    checked: false,
    groupId: 11,
    name: ' Mirzəyev Mirzə Nurəddin oğlu\r\n',
    position: 'AzencoASC, HİK-in sədri',
  },
  {
    order: 218,
    checked: false,
    groupId: 11,
    name: 'Novruzov Elşən Akif oğlu\r\n',
    position: 'Cənub ESMMC, HİK-in sədri',
  },
  {
    order: 219,
    checked: false,
    groupId: 11,
    name: ' Poladov Baləhməd Soltanmurad oğlu\r\n',
    position: '«Hərbiləşdirilmiş Mühafizə Dəstəsi» MMC, \r\nHİK-in sədri',
  },
  {
    order: 220,
    checked: false,
    groupId: 11,
    name: 'Vəliyev Vüqar Nəsib oğlu\r\n',
    position: '«Azərbaycan İES"MMC, HİK-in sədri',
  },
  {
    order: 221,
    checked: false,
    groupId: 12,
    name: 'Həsənov Tural Faiq oğlu',
    position: 'Azərbaycan Dəmiryolçularının Müstəqil Həmkarlar İttifaqının sədri',
  },
  {
    order: 222,
    checked: false,
    groupId: 12,
    name: 'Bədəlov Vaqif Məmməd Səyid oğlu',
    position: 'Azərbaycan Dəmiryolçularının Müstəqil Həmkarlar İttifaqının sədrinin müavini',
  },
  {
    order: 223,
    checked: false,
    groupId: 12,
    name: 'Babayeva Rəna Valeh qızı',
    position:
      'Azərbaycan Dəmiryolçularının Müstəqil Həmkarlar İttifaqının Təşkilat şöbəsinin müdiri',
  },
  {
    order: 224,
    checked: false,
    groupId: 12,
    name: 'Cəfərov Hüseyn Şahhüseyn oğlu',
    position:
      'Azərbaycan Dəmiryolçularının Müstəqil Həmkarlar İttifaqının baş texniki əmək müfəttişi',
  },
  {
    order: 225,
    checked: false,
    groupId: 12,
    name: 'Abbaszadə İlahə Abbas qızı',
    position: 'AHİK-in Üzv, tabe və tərəfdaş təşkilatlarla iş və maarifləndirmə şöbəsinin müdiri',
  },
  {
    order: 226,
    checked: false,
    groupId: 12,
    name: 'Zeynalova Mehriban Əli Hüseyn qızı',
    position: 'Azərbaycan Dəmiryolçularının Müstəqil Həmkarlar İttifaqının mütəxəssisi',
  },
  {
    order: 227,
    checked: false,
    groupId: 12,
    name: 'Quliyeva Samirə Rəhim qızı',
    position: 'Azərbaycan Dəmiryolçularının Müstəqil Həmkarlar İttifaqı, baş mühasib',
  },
  {
    order: 228,
    checked: false,
    groupId: 12,
    name: 'Behbudov Nazim Möhü oğlu',
    position: 'Azərbaycan Dəmiryolçularının Müstəqil Həmkarlar İttifaqı, baş mütəxəssis',
  },
  {
    order: 229,
    checked: false,
    groupId: 12,
    name: 'Əliyev İlqar Yusif oğlu',
    position: 'Yük daşımaları departamentinin Birləşmiş Həmkarlar İttifaqı Komitəsi sədri',
  },
  {
    order: 230,
    checked: false,
    groupId: 12,
    name: 'İsmayılov Niyaz Ənsər oğlu',
    position: 'Azərbaycan Dəmiryolçularının Müstəqil Həmkarlar İttifaqı iqtisadçı',
  },
  {
    order: 231,
    checked: false,
    groupId: 12,
    name: 'İsmayılova Aidə Səfər qızı',
    position: 'ADY aparat BHİK mütəxəssis',
  },
  {
    order: 232,
    checked: false,
    groupId: 12,
    name: 'İsmayılova Sevda Tofiq qızı',
    position: 'Azərbaycan Dəmiryolçularının Müstəqil Həmkarlar İttifaqı mühasib',
  },
  {
    order: 233,
    checked: false,
    groupId: 12,
    name: 'Nəzərov Namaz Veys oğlu',
    position: 'İnfrastruktur departamentinin Birləşmiş Həmkarlar İttifaqı Komitəsinin sədri',
  },
  {
    order: 234,
    checked: false,
    groupId: 12,
    name: 'Nəzərova Seylan Abbas qızı',
    position: ' Azərbaycan Dəmiryolçularının Müstəqil Həmkarlar İttifaqı, mühasib',
  },
  {
    order: 235,
    checked: false,
    groupId: 12,
    name: 'Səlimov Samir Ağabala oğlu',
    position: 'ADY aparat işçiləri BHİK sədri',
  },
  {
    order: 236,
    checked: false,
    groupId: 12,
    name: 'Zeynalova Ruqiyyə Kamran qızı',
    position:
      'Yük daşımaları departamenti Birləşmiş Həmkarlar İttifaqı Komitəsi Lokomotivlərin İstismar xidmətinin Biləcəri lokomotivlərin istismar deposunun Həmkarlar İttifaqı Komitəsi',
  },
  {
    order: 237,
    checked: false,
    groupId: 12,
    name: 'Süleymanov Vasif İsgəndər oğlu',
    position: 'Yük daşımaları departamentinin Birləşmiş Həmkarlar İttifaqı Komitəsi',
  },
  {
    order: 238,
    checked: false,
    groupId: 12,
    name: 'Abdullayev İsmayıl Qəhrəman oğlu',
    position: 'Mühafizə departamentinin Birləşmiş Həmkarlar İttifaqı Komitəsi sədr',
  },
  {
    order: 239,
    checked: false,
    groupId: 12,
    name: 'Məmmədov Elbariz İbrahim oğlu',
    position: 'İnfrastruktur departamentinin Birləşmiş Həmkarlar İttifaqı Komitəsi, mütəxəssis',
  },
  {
    order: 240,
    checked: false,
    groupId: 12,
    name: 'Əhmədov Samir Azər oğlu',
    position: 'Azərbaycan Dəmiryolçularının Müstəqil Həmkarlar İttifaqı hüquq müfəttişi',
  },
  {
    order: 241,
    checked: false,
    groupId: 13,
    name: 'Kərimov Hüseyn Qubad oğlu',
    position:
      'Azərbaycan Avtomobil Nəqliyyatı və Yol Təsərrüfatı İşçiləri Həmkarlar İttifaqının sədri ',
  },
  {
    order: 242,
    checked: false,
    groupId: 13,
    name: 'Hüseynov İlqar Böyükağa oğlu',
    position:
      'Azərbaycan Avtomobil Nəqliyyatı və Yol Təsərrüfatı İşçiləri Həmkarlar İttifaqının sədrinin müavini ',
  },
  {
    order: 243,
    checked: false,
    groupId: 13,
    name: 'Süleymanov Tural Epinus oğlu',
    position: 'AHİK-in Əmək və sosial-iqtisadi hüquqların  müdafiəsi şöbəsinin müdiri',
  },
  {
    order: 244,
    checked: false,
    groupId: 13,
    name: 'Hüseynova Sevda Ənvər qızı',
    position: 'Baş mühasib',
  },
  {
    order: 245,
    checked: false,
    groupId: 13,
    name: 'Məmmədzadə Emin Nizami oğlu',
    position: 'HİK sədri',
  },
  {
    order: 246,
    checked: false,
    groupId: 13,
    name: 'Əliyev Şahin Rahim oğlu',
    position: 'Maliyyə şöbəsinin',
  },
  {
    order: 247,
    checked: false,
    groupId: 13,
    name: 'Məmmədov Qoşqar Məmməd oğlu',
    position: 'Əməyin baş texniki müfəttişi',
  },
  {
    order: 248,
    checked: false,
    groupId: 13,
    name: 'Məcidov Vaqif Məcid oğlu',
    position: 'Hüquq müfəttişi',
  },
  {
    order: 249,
    checked: false,
    groupId: 13,
    name: 'Rzayev Rəşad Rəfail oğlu',
    position: 'Mütəxəssis',
  },
  {
    order: 250,
    checked: false,
    groupId: 13,
    name: 'Hacızadə Elnur Əhliman oğlu',
    position: 'Mütəxəssis',
  },
  {
    order: 251,
    checked: false,
    groupId: 13,
    name: 'Musayev Məhəmməd Nürəddin oğlu',
    position: 'HİK sədri',
  },
  {
    order: 252,
    checked: false,
    groupId: 13,
    name: 'Abbasov Elmir İlham oğlu',
    position: 'HİK sədri',
  },
  {
    order: 253,
    checked: false,
    groupId: 13,
    name: 'Mahmudov Müşfiq Əlövsət oğlu',
    position: 'HİK sədri',
  },
  {
    order: 254,
    checked: false,
    groupId: 13,
    name: 'Muradzadə Natiq Muradxan oğlu',
    position: 'HİK sədri',
  },
  {
    order: 255,
    checked: false,
    groupId: 13,
    name: 'Səmədova Əminə İsmayıl qızı',
    position: 'HİK sədri',
  },
  {
    order: 256,
    checked: false,
    groupId: 13,
    name: 'Kiryuxina Alla Aleksandrovna',
    position: 'HİK sədri',
  },
  {
    order: 257,
    checked: false,
    groupId: 13,
    name: 'Quliyeva Adilə Məmmədqulu qızı',
    position: 'HİK sədri',
  },
  {
    order: 258,
    checked: false,
    groupId: 13,
    name: 'Abdullayeva Aynurə Mürvət qızı',
    position: 'HİK sədri',
  },
  {
    order: 259,
    checked: false,
    groupId: 13,
    name: 'Mirzəyeva Həcər Kərim qızı',
    position: 'HİK sədri',
  },
  {
    order: 260,
    checked: false,
    groupId: 13,
    name: 'Hüseynov Amil Canbaxış oğlu',
    position: 'HİK sədri',
  },
  {
    order: 261,
    checked: false,
    groupId: 14,
    name: 'İsmayılov Mehman Heydər oğlu',
    position:
      'Azərbaycan Respublikası Fövqəladə Hallar Nazirliyi İşçilərinin Həmkarlar İttifaqının sədri',
  },
  {
    order: 262,
    checked: false,
    groupId: 14,
    name: 'Fəxrəddinli Fərid Fəxrəddin oğlu',
    position:
      'Azərbaycan Respublikası Fövqəladə Hallar Nazirliyi İşçilərinin Həmkarlar İttifaqının mütəxəssisi',
  },
  {
    order: 263,
    checked: false,
    groupId: 14,
    name: 'Abbasov Pərviz Əli oğlu',
    position: 'HİK-in sədri',
  },
  {
    order: 264,
    checked: false,
    groupId: 14,
    name: 'Maqsudova Güldəstə Bilal qızı',
    position: 'HİK-in sədri',
  },
  {
    order: 265,
    checked: false,
    groupId: 14,
    name: 'Cəfərov Məhəmməd Əsgər oğlu',
    position: 'AHİK-in Satınalma və təchizat şöbəsinin müdiri\r\n',
  },
  {
    order: 266,
    checked: false,
    groupId: 14,
    name: 'Xanbabayeva Afət Əjdər qızı',
    position: 'FHN Hİ sədr müavini',
  },
  {
    order: 267,
    checked: false,
    groupId: 14,
    name: 'Həmzəyev Azad Səadət oğlu',
    position: 'FHN Hİ mütəxəssis',
  },
  {
    order: 268,
    checked: false,
    groupId: 14,
    name: 'Ağayev Teymur Anar oğlu',
    position: 'FHN Hİ mütəxəssis',
  },
  {
    order: 269,
    checked: false,
    groupId: 14,
    name: 'Bəşirov Vüqar Tahir oğlu',
    position: 'FHN Hİ mütəxəssis',
  },
  {
    order: 270,
    checked: false,
    groupId: 14,
    name: 'Kərimli Bəhruz Telman oğlu',
    position: 'FHN Hİ mütəxəssis',
  },
  {
    order: 271,
    checked: false,
    groupId: 14,
    name: 'Məmmədov Vüqar Rəhim oğlu',
    position: 'HİK-in sədri',
  },
  {
    order: 272,
    checked: false,
    groupId: 14,
    name: 'Məmmədova Nəzakət Vəli qızı',
    position: 'HİK-in sədri',
  },
  {
    order: 273,
    checked: false,
    groupId: 14,
    name: 'Qaratov Məmmədəli Hacımirzə oğlu',
    position: 'HİK-in sədri',
  },
  {
    order: 274,
    checked: false,
    groupId: 14,
    name: 'Zeynalov Tural İntiqam oğlu',
    position: 'HİK-in sədri',
  },
  {
    order: 275,
    checked: false,
    groupId: 14,
    name: 'Qocayev Tural Qüdrət oğlu',
    position: 'HİK-in sədri',
  },
  {
    order: 276,
    checked: false,
    groupId: 14,
    name: 'Cəmilov Vüqar Həsən oğlu',
    position: 'HİK-in sədri',
  },
  {
    order: 277,
    checked: false,
    groupId: 14,
    name: 'Rüstəmov Fariz Zahid oğlu',
    position: 'HİK-in sədri',
  },
  {
    order: 278,
    checked: false,
    groupId: 14,
    name: 'Zehirov Elməddin Kamran oğlu',
    position: 'HİK-in sədri',
  },
  {
    order: 279,
    checked: false,
    groupId: 14,
    name: 'Vəliyeva Esmira Vəli qızı',
    position: 'HİK-in sədri',
  },
  {
    order: 280,
    checked: false,
    groupId: 14,
    name: 'Əzimova Sima Rəhim qızı',
    position: 'HİK-in sədri',
  },
  {
    order: 281,
    checked: false,
    groupId: 15,
    name: 'Əsədov Mübariz Qədir oğlu',
    position: 'Azərbaycan Aviasiya İşçilərinin Həmkarlar İttifaqının sədri ',
  },
  {
    order: 282,
    checked: false,
    groupId: 15,
    name: 'İlyasov Kamil Vaqif oğlu',
    position: 'HİK sədri',
  },
  {
    order: 283,
    checked: false,
    groupId: 15,
    name: 'Babayeva Bənövşə Bəhman qızı',
    position: 'AHİK-in İnsan resursları şöbəsinin müdiri',
  },
  {
    order: 284,
    checked: false,
    groupId: 15,
    name: 'Məmmədov Seyfəli Ernest oğlu',
    position: 'HİK sədri',
  },
  {
    order: 285,
    checked: false,
    groupId: 15,
    name: 'Mirzəyeva Sitarə Tariyel qızı',
    position: '"Azal" QSC. Psixoloq',
  },
  {
    order: 286,
    checked: false,
    groupId: 15,
    name: 'Əhmədova Samirə Sədrəddin qızı',
    position: 'Sədr müavini',
  },
  {
    order: 287,
    checked: false,
    groupId: 15,
    name: 'Heydərova İlhamə Kamal qızı',
    position: 'Təşkilat şöbəsinin müdiri',
  },
  {
    order: 288,
    checked: false,
    groupId: 15,
    name: 'Qəribov Habil Ataş oğlu',
    position: 'Baş texniki əmək müfəttişi',
  },
  {
    order: 289,
    checked: false,
    groupId: 15,
    name: 'Aslanov Rasim Şakir oğlu',
    position: 'Hüquq müfəttişi',
  },
  {
    order: 290,
    checked: false,
    groupId: 15,
    name: 'İskəndərov Elçin Xanbala oğlu',
    position: 'Sağlamlığın mühafizəsi üzrə mütəxəssis',
  },
  {
    order: 291,
    checked: false,
    groupId: 15,
    name: 'Məmmədov Vaqif Vidadi oğlu',
    position: 'HİK sədri',
  },
  {
    order: 292,
    checked: false,
    groupId: 15,
    name: 'Süleymanov Qalib Çıraq oğlu',
    position: 'HİK sədri',
  },
  {
    order: 293,
    checked: false,
    groupId: 15,
    name: 'Əliyeva Məlahət Faiq qızı',
    position: 'HİK sədri',
  },
  {
    order: 294,
    checked: false,
    groupId: 15,
    name: 'Sultanov Fərrux Azanəli oğlu',
    position: 'HİK sədri',
  },
  {
    order: 295,
    checked: false,
    groupId: 15,
    name: 'Əsgərov Zaur Yamən oğlu',
    position: 'HİK sədri',
  },
  {
    order: 296,
    checked: false,
    groupId: 15,
    name: 'Əhmədova Məhsəti Rasim qızı',
    position: 'HİK sədri',
  },
  {
    order: 297,
    checked: false,
    groupId: 15,
    name: 'Allahverdiyeva Zenfira Əsədulla qızı',
    position: 'Böyük mühasib',
  },
  {
    order: 298,
    checked: false,
    groupId: 15,
    name: 'İsayeva Nəzirə Mehman qızı',
    position: 'Böyük mühasib',
  },
  {
    order: 299,
    checked: false,
    groupId: 15,
    name: 'Rüstəmova Sevinc Tahir qızı',
    position: 'Böyük mühasib',
  },
  {
    order: 300,
    checked: false,
    groupId: 15,
    name: 'Qafarov Nizami Nifdəli oğlu',
    position: 'Təlimatçı',
  },
  {
    order: 301,
    checked: false,
    groupId: 16,
    name: 'Allahverdiyev Səməd Oysar oğlu           ',
    position: 'Azərbaycan Dəniz Nəqliyyatı İşçiləri Həmkarlar İttifaqının sədri',
  },
  {
    order: 302,
    checked: false,
    groupId: 16,
    name: 'Vəliyev Etibar Əhməd oğlu                               ',
    position: 'Azərbaycan Dəniz Nəqliyyatı İşçiləri Həmkarlar İttifaqının sədrinin müavini',
  },
  {
    order: 303,
    checked: false,
    groupId: 16,
    name: 'Cəfərov Qəhrəman Cəfəralı oğlu                 ',
    position: 'Azərbaycan Dəniz Nəqliyyatı İşçiləri Həmkarlar İttifaqının sədrinin müavini',
  },
  {
    order: 304,
    checked: false,
    groupId: 16,
    name: 'İmanova Arzu Cahangir qızı  ',
    position: 'AHİK-in Sənədlərlə və vətəndaşların müraciətləri ilə iş şöbəsinin müdiri ',
  },
  {
    order: 305,
    checked: false,
    groupId: 16,
    name: 'Mirzəyev Məhərrəm Ələmdar oğlu',
    position: 'Şöbə müdiri ',
  },
  {
    order: 306,
    checked: false,
    groupId: 16,
    name: 'Sadıqova Kəmalə Mehdi qızı',
    position: 'Mühəndis \r\nkonstrukktor',
  },
  {
    order: 307,
    checked: false,
    groupId: 16,
    name: 'Həsənova Nigar Abduləhəd qızı',
    position: 'Mütəxəssis',
  },
  {
    order: 308,
    checked: false,
    groupId: 16,
    name: 'Mustafayev Əli Nəbi oğlu',
    position: 'Komitə sədri',
  },
  {
    order: 309,
    checked: false,
    groupId: 16,
    name: 'Rüstəmov Şahmərdan Səhralı oğlu',
    position: 'Komitə sədri',
  },
  {
    order: 310,
    checked: false,
    groupId: 16,
    name: 'Muradov Azad Almas oğlu',
    position: 'Komitə sədri',
  },
  {
    order: 311,
    checked: false,
    groupId: 16,
    name: 'Cəfərov Rasim Əşrəf oğlu',
    position: 'Mütəxəssis',
  },
  {
    order: 312,
    checked: false,
    groupId: 16,
    name: 'İqnatoviç Elina Yuryevna',
    position: 'Baş mühasib ',
  },
  {
    order: 313,
    checked: false,
    groupId: 16,
    name: 'Abbasbəyli Sevinc Mirrəhim qızı',
    position: 'Baş mütəxəssis',
  },
  {
    order: 314,
    checked: false,
    groupId: 16,
    name: 'Hüseynova Afaq Səməd qızı',
    position: 'Mütəxəssis',
  },
  {
    order: 315,
    checked: false,
    groupId: 16,
    name: 'Mahmudova Ünay Mirmöhsüm qızı',
    position: 'Mütəxəssis',
  },
  {
    order: 316,
    checked: false,
    groupId: 16,
    name: 'Mahmudov Rahib Adil oğlu',
    position: 'Əmək Müfəttişi',
  },
  {
    order: 317,
    checked: false,
    groupId: 16,
    name: 'Əmirov İlqar Əmirxan oğlu',
    position: 'Hüquq Müfəttişi',
  },
  {
    order: 318,
    checked: false,
    groupId: 16,
    name: 'Süleymanlı Hüseyn Elşən oğlu',
    position: 'Kompüter operatoru',
  },
  {
    order: 319,
    checked: false,
    groupId: 16,
    name: 'Məmmədov Sahib Ağalar oğlu',
    position: 'Baş mütəxəssis',
  },
  {
    order: 320,
    checked: false,
    groupId: 16,
    name: 'Qafarlı Əli Aydın oğlu',
    position: 'Baş mütəxəssis',
  },
  {
    order: 321,
    checked: false,
    groupId: 17,
    name: 'Mahmudov Seymur Nazim oğlu ',
    position: 'Azərbaycan Müdafiə Sənayesi İşçiləri  Həmkarlar İttifaqının sədri',
  },
  {
    order: 322,
    checked: false,
    groupId: 17,
    name: 'Rəfiyev İlqar Məzahir oğlu ',
    position: 'Azərbaycan Müdafiə Sənayesi İşçiləri  Həmkarlar İttifaqının sədrinin müavini',
  },
  {
    order: 323,
    checked: false,
    groupId: 17,
    name: 'Kazımov Məzahir Qardaş oğlu ',
    position: '"İqlim EİM" MMC HİT-in sədri',
  },
  {
    order: 324,
    checked: false,
    groupId: 17,
    name: 'Əmişov Rəhim Qurban oğlu ',
    position: 'RK-aparatı əməyin hüquq müfəttişi',
  },
  {
    order: 325,
    checked: false,
    groupId: 17,
    name: 'Əliyev Əfqan Bayram oğlu ',
    position: 'AHİK sədrinin müşaviri',
  },
  {
    order: 326,
    checked: false,
    groupId: 17,
    name: 'Hüseynova Gülnarə Fazil qızı ',
    position:
      'AHİK-in Gənclər, sosial layihələr və gender məsələləri ilə iş şöbəsinin müdirinin müavini, şöbə müdirinin vəzifəsini müvəqqəti i.e.',
  },
  {
    order: 327,
    checked: false,
    groupId: 17,
    name: 'Hüseynova Aygün Aydın qızı ',
    position: 'RK aparatı mütəxəssis',
  },
  {
    order: 328,
    checked: false,
    groupId: 17,
    name: 'Məmmədov Şirin Hafiz oğlu ',
    position: 'MAKA HİT, sədr',
  },
  {
    order: 329,
    checked: false,
    groupId: 17,
    name: 'İbrəhimov Fərzulla Feyzulla oğlu ',
    position: 'Sənayecihaz EİM HİK, mütəxəssis',
  },
  {
    order: 330,
    checked: false,
    groupId: 17,
    name: 'Əhədli Rəşid Gülhüseyn oğlu',
    position: 'Zireh MMC, şöbə müdiri,HİT sədri',
  },
  {
    order: 331,
    checked: false,
    groupId: 17,
    name: 'Cəbiyev Şahalı Feyzulla oğlu ',
    position: 'Cihaz İB,şöbə müdiri,Hİ təmsilçisi',
  },
  {
    order: 332,
    checked: false,
    groupId: 17,
    name: 'Qurbanova Afət Məmməd qızı ',
    position: 'İqlim EİM  şöbə müdiri, Hİ təmsilcişi',
  },
  {
    order: 333,
    checked: false,
    groupId: 17,
    name: 'Cəfərova İlkanə Rəhim qızı ',
    position: 'İqlim EİMMMC HİT, baş mühasib',
  },
  {
    order: 334,
    checked: false,
    groupId: 17,
    name: 'Haqverdiyeva Aysel Vahid qızı ',
    position: 'RK aparatı, maliyyə şöbəsinin müdiri',
  },
  {
    order: 335,
    checked: false,
    groupId: 17,
    name: 'İsmayılov Vüqar Calal oğlu ',
    position: 'TMİ. mütəxəssis,HİT sədri',
  },
  {
    order: 336,
    checked: false,
    groupId: 17,
    name: 'Bayramov Canpolad Məmməd oğlu ',
    position: 'ETİ, şöbə müdiri, HİT sədri',
  },
  {
    order: 337,
    checked: false,
    groupId: 17,
    name: 'Mirişov Ehtiram Zakir oğlu ',
    position: 'MSN aparatı, sektor müdiri, HİT sədri',
  },
  {
    order: 338,
    checked: false,
    groupId: 17,
    name: 'Heydərov Səxavət Əli oğlu ',
    position: 'RK aparatı, baş texniki əmək müfəttişi',
  },
  {
    order: 339,
    checked: false,
    groupId: 17,
    name: 'Eyubova İradə Novruz qızı ',
    position: 'İqlim EİM MMC, mühəndis, HİTsədrinin müavini',
  },
  {
    order: 340,
    checked: false,
    groupId: 17,
    name: 'Məmmədova Yeganə Bülhan qızı ',
    position: 'Sənayecihaz EİM,  mütəxəssis, Hİ təmsilçisi',
  },
  {
    order: 341,
    checked: false,
    groupId: 18,
    name: 'Mərdanov Arif Fərman oğlu',
    position: 'Metropoliten İşçiləri Həmkarlar İttifaqının sədri',
  },
  {
    order: 342,
    checked: false,
    groupId: 18,
    name: 'Əhmədov Bəhruz Yaqub oğlu',
    position: 'Metropoliten İşçiləri Həmkarlar İttifaqının sədrinin müavini',
  },
  {
    order: 343,
    checked: false,
    groupId: 18,
    name: 'Bayramova Şəfa Etibar qızı',
    position: 'AHİK-in Hüquq şöbəsinin müdiri',
  },
  {
    order: 344,
    checked: false,
    groupId: 18,
    name: 'Həsənov Anar Paşa oğlu',
    position: 'Depolar Üzrə İş Departamenti HİK sədri',
  },
  {
    order: 345,
    checked: false,
    groupId: 18,
    name: 'Mustafayeva Ofeliya Bəkir qızı',
    position: 'Bakı Metropoliteni QSC-nin İdarə Aparatının HİK-sədri',
  },
  {
    order: 346,
    checked: false,
    groupId: 18,
    name: 'Mirzəyeva Elza Mürseyib qızı',
    position: 'Hərəkət Xidmətinin HİK-sədri',
  },
  {
    order: 347,
    checked: false,
    groupId: 18,
    name: 'Qənbərli Elnur Məzahir oğlu',
    position: 'Hərəkət Qatarlarının İstismarı üzrə İş Departamentinin HİK-sədri',
  },
  {
    order: 348,
    checked: false,
    groupId: 18,
    name: 'Ramazanova Rahilə Mustafa qızı',
    position: 'Eskalator Xidmətinin HİK sədri',
  },
  {
    order: 349,
    checked: false,
    groupId: 18,
    name: 'Nəsibov Səməndər İlham oğlu',
    position: 'Dəmir Beton Konstruksiyalar İstehsalatı Sahəsi Hik sədri',
  },
  {
    order: 350,
    checked: false,
    groupId: 18,
    name: 'Şahverdiyev Emin Orduxan oğlu',
    position: 'Elektrik Təchizatı Xidməti HİK sədri',
  },
  {
    order: 351,
    checked: false,
    groupId: 18,
    name: 'Həsənli Qədir Eldar oğlu',
    position: 'Elektromexanika Xidməti HİKsədri',
  },
  {
    order: 352,
    checked: false,
    groupId: 18,
    name: 'Məmmədova Cəmilə Tahir qızı',
    position: 'Tunel Qurğuları Xidməti HİK sədri',
  },
  {
    order: 353,
    checked: false,
    groupId: 18,
    name: 'Nuriyev Anar Adil oğlu',
    position: 'İşarəvermə və Rabitə Xidməti HİK sədri',
  },
  {
    order: 354,
    checked: false,
    groupId: 18,
    name: 'Pirməmmədova Lalə Zimir qızı',
    position: 'Birləşmiş Emalatxanalar HİK sədri',
  },
  {
    order: 355,
    checked: false,
    groupId: 18,
    name: 'Əliyev Əli Akif oğlu',
    position: 'Mühafizə Xidməti HİK sədri',
  },
  {
    order: 356,
    checked: false,
    groupId: 18,
    name: 'Əzimova Arzu Məzahir oğlu',
    position: 'Yaşıllaşdırma və Vaqonların Təmizlik Təsərrüfatı Xidməti HİK sədri',
  },
  {
    order: 357,
    checked: false,
    groupId: 18,
    name: 'Məmmədov Nazim Məzahir oğlu',
    position: 'Avtomotonəqliyyat Kolonu HİK sədri',
  },
  {
    order: 358,
    checked: false,
    groupId: 18,
    name: 'Oruclu Bəhruz Mirzəli oğlu',
    position: 'Yol Xidməti HİK sədri, İTŞ Aparıcı Mühəndis ',
  },
  {
    order: 359,
    checked: false,
    groupId: 18,
    name: 'Məmmədov Ərşad Köçəri oğlu',
    position: 'Mərkəzləşmiş Dispetçer Xidməti HİK sədri',
  },
  {
    order: 360,
    checked: false,
    groupId: 18,
    name: 'Müslümova Nərminə Əjdərovna',
    position: 'Bakımetrolayihə İnstitunun HİK sədri',
  },
  {
    order: 361,
    checked: false,
    groupId: 19,
    name: 'Həsənov Sənan Səməndər oğlu',
    position: 'AMEA Azad Həmkarlar İttifaqının sədri',
  },
  {
    order: 362,
    checked: false,
    groupId: 19,
    name: 'Əmirova Şəhla Tofiq qızı',
    position: 'AMEA Azad Həmkarlar İttifaqının sədrinin müavini',
  },
  {
    order: 363,
    checked: false,
    groupId: 19,
    name: 'Əliyev İlham Malik oğlu',
    position: 'AMEA Azad Həmkarlar İttifaqının Rəyasət Heyətinin üzvü',
  },
  {
    order: 364,
    checked: false,
    groupId: 19,
    name: 'Fəthi-Xoşqinəbi Leyla Əsəd qızı',
    position: 'AHİK-in Beynəlxalq Əlaqələr şöbəsinin müdiri',
  },
  {
    order: 365,
    checked: false,
    groupId: 19,
    name: 'Həsənov Şövqü Vaqif oğlu',
    position: 'Tarix və Etnologiya İnstitutunun HT sədri ',
  },
  {
    order: 366,
    checked: false,
    groupId: 19,
    name: 'Cabbarova Aygün Nail qızı',
    position: 'AMEA AHİ-nin mütəxəssis və beynəlxalq məsələlər üzrə məsul şəxsi',
  },
  {
    order: 367,
    checked: false,
    groupId: 19,
    name: 'Mahmud Aynur Vaqif qızı',
    position: 'AMEA Rəyasət Heyətinin Aparatının HT sədri ',
  },
  {
    order: 368,
    checked: false,
    groupId: 19,
    name: 'Qaravəliyev Etibar Sayad oğlu ',
    position: 'Respublika Seysmoloji Xidmət Mərkəzinin HT sədri ',
  },
  {
    order: 369,
    checked: false,
    groupId: 19,
    name: 'Hacıyeva Nailə Natiq qızı',
    position: 'Gəncə bölməsinin Aparatının HT sədri',
  },
  {
    order: 370,
    checked: false,
    groupId: 19,
    name: 'Talıblı Sübhan Ələkbər oğlu',
    position: 'Şərqşünaslıq İnstitutunun HT sədri ',
  },
  {
    order: 371,
    checked: false,
    groupId: 19,
    name: 'Əhmədova Asya Humayaq qızı',
    position: 'Fəlsəfə və Sosiologiya İnstitutunun HT sədri ',
  },
  {
    order: 372,
    checked: false,
    groupId: 19,
    name: 'Musayev Şahbaz Şamı oğlu',
    position: 'Ədəbiyyat İnstitutunun HT sədri ',
  },
  {
    order: 373,
    checked: false,
    groupId: 19,
    name: 'Mahmudova Qətibə Çingiz qızı',
    position: 'Dilçilik İnstitutunun HT sədri ',
  },
  {
    order: 374,
    checked: false,
    groupId: 19,
    name: 'Əliyeva Pərvanə Əli qızı',
    position: 'Memarlıq və İncəsənət İnstitutunun HT sədri ',
  },
  {
    order: 375,
    checked: false,
    groupId: 19,
    name: 'Əliyeva Samirə Ağababa qızı',
    position: 'Əlyazmalar İnstitutunun HT sədri ',
  },
  {
    order: 376,
    checked: false,
    groupId: 19,
    name: 'İbrahimova Aynur Aydın qızı',
    position: 'Folklor İnstitutu HT sədri ',
  },
  {
    order: 377,
    checked: false,
    groupId: 19,
    name: 'İbrahimov Böyükağa Rahib oğlu',
    position: '“Azərbaycan Milli Ensiklopediyası” Elmi Mərkəzinin HT sədri ',
  },
  {
    order: 378,
    checked: false,
    groupId: 19,
    name: 'Rəhimova Günel Rahim qızı',
    position: 'Mərkəzi Elmi Kitabxananın HT sədri ',
  },
  {
    order: 379,
    checked: false,
    groupId: 19,
    name: 'İmanova Səbinə Kamandar qızı',
    position: ' “Elm” Nəşriyyatının HT sədri ',
  },
  {
    order: 380,
    checked: false,
    groupId: 19,
    name: 'Məmmədova Leyla Cəlil qızı',
    position: 'Hüquq və İnsan Haqları İnsitutunun HT sədri    ',
  },
  {
    order: 381,
    checked: false,
    groupId: 20,
    name: 'Abbasov  Asif  Nuru  oğlu',
    position: 'Baku Steel Company İşçiləri Həmkarlar İttifaqı Birliyinin sədri',
  },
  {
    order: 382,
    checked: false,
    groupId: 20,
    name: 'Məmmədov  Hüseyn Salman  oğlu',
    position: 'Azərboru sahəsinin HİK-nin sədri',
  },
  {
    order: 383,
    checked: false,
    groupId: 20,
    name: 'Quliyev Firudin Şahverdi oğlu',
    position: 'Poladəritmə sexinin texnoloqu',
  },
  {
    order: 384,
    checked: false,
    groupId: 20,
    name: 'Əliyev  Abbas  Murad  oğlu',
    position: 'Azərbaycan Həmkarlar İttifaqları Konfederasiyasının Aparat rəhbərinin müavini',
  },
  {
    order: 385,
    checked: false,
    groupId: 20,
    name: 'Sanılı  Azər Malik  oğlu',
    position: 'AHİK-in İnformasiya texnoloqiyaları  və rəqəmsal  idarəetmə şöbəsinin müdiri  ',
  },
  {
    order: 386,
    checked: false,
    groupId: 20,
    name: 'Hasilova  Səadət  Zakir  qızı',
    position: 'Azərbaycan Həmkarlar İttifaqları Konfederasiyasının Maliyyə şöbəsinin müdiri',
  },
  {
    order: 387,
    checked: false,
    groupId: 20,
    name: 'Süleymanov  Şahin  Şüleyman oğlu',
    position: 'Sahə rəisi',
  },
  {
    order: 388,
    checked: false,
    groupId: 20,
    name: 'Məmmədov  Xeybər  Mehdi  oğlu',
    position: 'İstehsalat  üzrə  mühəndis',
  },
  {
    order: 389,
    checked: false,
    groupId: 20,
    name: 'Həsənov  Tahir   Allahyar  oğlu',
    position: 'Usta',
  },
  {
    order: 390,
    checked: false,
    groupId: 20,
    name: 'Musayev  Abbas  Malik  oğlu',
    position: 'Yayma-3 sahəsi, qaynaqçı',
  },
  {
    order: 391,
    checked: false,
    groupId: 20,
    name: 'Zülfüqarov  Nahid  Əmrulla  oğlu',
    position: 'Usta',
  },
  {
    order: 392,
    checked: false,
    groupId: 20,
    name: 'Mehdiyev Seyfəddin Telman oğ.',
    position: 'Baş usta ',
  },
  {
    order: 393,
    checked: false,
    groupId: 20,
    name: 'Heydərov  Tural  Nazim  oğlu',
    position: 'Nəzarətçi/Sertifikatlaşdırma üzrə  mütəxəssis',
  },
  {
    order: 394,
    checked: false,
    groupId: 20,
    name: 'Quliyev  Əvəz  Məhərrəm oğ.',
    position: 'Texnoloq',
  },
  {
    order: 395,
    checked: false,
    groupId: 20,
    name: 'Ramazanov  Rəşad Əlixan  oğlu',
    position: 'Sahə  rəisi',
  },
  {
    order: 396,
    checked: false,
    groupId: 20,
    name: 'Xəlilova  Ülviyyə  Savalan  qızı',
    position: 'Rəis',
  },
  {
    order: 397,
    checked: false,
    groupId: 20,
    name: 'Məlikov  Gündüz  Bəybala oğlu',
    position: 'Baş  müfəttiş',
  },
  {
    order: 398,
    checked: false,
    groupId: 20,
    name: 'Cavadov  Elçin  Teyyub oğlu',
    position: 'Satınalmaların təşkili üzrəaparıcı  mütəxəssis',
  },
  {
    order: 399,
    checked: false,
    groupId: 20,
    name: 'Sadıqov  Seymur  Əliyar  oğlu',
    position: 'Böyük  usta',
  },
  {
    order: 400,
    checked: false,
    groupId: 20,
    name: 'Yusifova  Nailə  Sabir  qızı',
    position: 'Lobaratoriya müdiri',
  },
  {
    order: 401,
    checked: false,
    groupId: 21,
    name: 'Rüstəmov Emil Əli oğlu',
    position: 'Azərbaycan Turizm Müəssisələri İşçiləri Həmkarlar İttifaqı Birliyinin sədri',
  },
  {
    order: 402,
    checked: false,
    groupId: 21,
    name: 'Cəfərov Nəsimi Mikayıl oğlu',
    position:
      'Azərbaycan Turizm Müəssisələri İşçiləri Həmkarlar İttifaqı Birliyinin sədrinin müavini',
  },
  {
    order: 403,
    checked: false,
    groupId: 21,
    name: 'Abbasova Cəmilə Sevindik qızı',
    position: 'AR Dövlət Turizm Agentliyinin Ümumi şöbəsinin müdiri',
  },
  {
    order: 404,
    checked: false,
    groupId: 21,
    name: 'Aşurova Arzu Səmidağa qızı ',
    position: 'İnsan resursları şöbəsinin baş mütəxəssisi, ATMU, HİK sədr',
  },
  {
    order: 405,
    checked: false,
    groupId: 21,
    name: 'Mustafayev Rəhim Rəftar oğlu',
    position: 'Şahdağ QSC-nin HİK sədri',
  },
  {
    order: 406,
    checked: false,
    groupId: 21,
    name: 'Hüseynova Kəmalə Çingiz qızı ',
    position:
      'Azərbaycan Turizm Bürosunun İnsan resurslarının idarə edilməsi və inzibati işlər departamentinin direktoru',
  },
  {
    order: 407,
    checked: false,
    groupId: 21,
    name: 'Məmmədova Elnurə Fərman qızı',
    position: 'Milli Kulinariya Mərkəzinin baş mütəxəssisi',
  },
  {
    order: 408,
    checked: false,
    groupId: 21,
    name: 'Əliyev Zöhrab Adil oğlu ',
    position: 'Bədən Tərbiyəsi Rəhbəri ',
  },
  {
    order: 409,
    checked: false,
    groupId: 21,
    name: 'Oruclu Səbinə Allahverdi qızı',
    position: 'Yanar dağ muzeyi baş fond mühafizəçisi ',
  },
  {
    order: 410,
    checked: false,
    groupId: 21,
    name: 'Abbasbəyli Səmayə Arif qızı',
    position:
      'Azərbaycan Turizm və Menecment Universitetinin Tələbə Həmkarlar ittifaqının sədri, Tədris-metodiki şöbəsinin baş mütəxəssisi',
  },
  {
    order: 411,
    checked: false,
    groupId: 21,
    name: 'Əliyeva Ayan Zaur qızı',
    position: 'Azərbaycan Turizm və Menecment Universitetinin tələbəsi',
  },
  {
    order: 412,
    checked: false,
    groupId: 21,
    name: 'İmanova Nəzrin Təbriz qızı',
    position: 'Azərbaycan Turizm və Menecment Universitetinin tələbəsi',
  },
  {
    order: 413,
    checked: false,
    groupId: 21,
    name: 'Qasımlı Hacı Hacıbala oğlu',
    position:
      'Elmi Tədqiqatlar və Akademik Təhsil Mərkəzinin Magistratura və Doktorantura bölməsinin rəhbəri, ATMU HİK, ',
  },
  {
    order: 414,
    checked: false,
    groupId: 21,
    name: 'Babayev Rauf Mirəcəb oğlu',
    position: 'Azərbaycan Turizm Müəssisələri İşçiləri Həmkarlar İttifaqı Birliyinin mühasibi',
  },
  {
    order: 415,
    checked: false,
    groupId: 21,
    name: 'Həmidov Canpolad Rəhbər oğlu',
    position: 'Mingəçevir Turizm Kollecinin HİK sədri',
  },
  {
    order: 416,
    checked: false,
    groupId: 21,
    name: 'Ağalarov Elşən Yusif oğlu',
    position: 'Qoruqları İdarəetmə Mərkəzinin HİK sədri',
  },
  {
    order: 417,
    checked: false,
    groupId: 21,
    name: 'Hüseynova Aygün Kəmaləddin qızı',
    position: 'Atəşgah muzey kompleksinin HİK sədri',
  },
  {
    order: 418,
    checked: false,
    groupId: 21,
    name: 'Kərimov Fərid Ceyhun oğlu',
    position: 'Şahdağ QSC-nin baş mühasib',
  },
  {
    order: 419,
    checked: false,
    groupId: 21,
    name: 'Şahbazov Turan Rövşən oğlu',
    position: 'Bakı Turizm Peşə məktəbinin tələbəsi, Hİ fəalı',
  },
  {
    order: 420,
    checked: false,
    groupId: 21,
    name: 'Əhmədzadə Lətifə Oruc qızı',
    position: 'Mingəçevir Turizm Kollecinin THİK sədri',
  },
];
